### ISSUE TITLE
Build problems.

### ISSUE THREAD

**Issue by pheaver** [emacs-eclim/emacs-eclim#33] opened 2017-01-12 19:00 UTC
First, ```make``` fails because cask is not available. I had never heard of it, and there are no instructions for obtaining it. It seems better supported on OS X (via homebrew), it's not in Ubuntu, so I'm not thrilled about having to install it manually.

After installing cask. ```make``` fails because the package ```f``` is not available. Installing it manually does not fix the problem because the makefile run emacs with -Q.

I don't have a working eclim. Every version that I've tried (0.3 from melpa-stable, some latest builds from melpa) is broken. Building manually is the only way I will be able to get a working eclim...

**Comment by luisgerhorst** [comment] 2017-01-12 19:07
I'm sorry for the trouble you're having. I would try installing [all dependencies from melpa](https://gist.github.com/luisgerhorst/b8473dbcbfa731d1f56e1b60bf8ffd17#file-init-el-L35) and then just loading eclim via git, you should not have to use the Makefile / Cask for this.

**Comment by pheaver** [comment] 2017-01-12 19:11
Ok, that worked. I figured I'd want to build it for performance, but I guess the elisp isn't doing that much work (it's all in the eclimd backend).

**Comment by luisgerhorst** [comment] 2017-01-12 19:14
`make compile` should work even if you did not install cask. Just `$ make` runs the tests.

**Comment by luisgerhorst** [comment] 2017-01-12 19:15
I don't think compiling makes a noticeable speed improvement on this project.

**Comment by pheaver** [comment] 2017-01-12 19:18
```make compile``` does not work without cask, and here's what happens with cask:

```
cask exec emacs -Q -batch -L .  -l maint/eclim-compile.el -f eclim/batch-byte-compile ac-emacs-eclim.el company-emacs-eclim.el eclim-ant.el eclim-common.el eclim-completion.el eclim-debug.el eclim-java-run.el eclim-java.el eclim-macros.el eclim-maven.el eclim-pkg.el eclim-problems.el eclim-project.el eclim-scala.el eclim.el eclimd.el
Compiling /home/pweaver/emacs-eclim/ac-emacs-eclim.el...

In toplevel form:
ac-emacs-eclim.el:34:1:Error: Cannot open load file: no such file or directory, s
Compiling /home/pweaver/emacs-eclim/company-emacs-eclim.el...

In toplevel form:
company-emacs-eclim.el:29:1:Error: Cannot open load file: no such file or directory, s
Compiling /home/pweaver/emacs-eclim/eclim-ant.el...

In toplevel form:
eclim-ant.el:31:1:Error: Cannot open load file: no such file or directory, popup
Compiling /home/pweaver/emacs-eclim/eclim-common.el...

In toplevel form:
eclim-common.el:37:1:Error: Cannot open load file: no such file or directory, popup
Compiling /home/pweaver/emacs-eclim/eclim-completion.el...

In toplevel form:
eclim-completion.el:36:1:Error: Cannot open load file: no such file or directory, s
Compiling /home/pweaver/emacs-eclim/eclim-debug.el...

In toplevel form:
eclim-debug.el:36:1:Error: Cannot open load file: no such file or directory, popup
Compiling /home/pweaver/emacs-eclim/eclim-java-run.el...

In toplevel form:
eclim-java-run.el:35:1:Error: Cannot open load file: no such file or directory, popup
Compiling /home/pweaver/emacs-eclim/eclim-java.el...

In toplevel form:
eclim-java.el:34:1:Error: Cannot open load file: no such file or directory, dash
Compiling /home/pweaver/emacs-eclim/eclim-macros.el...
Wrote /home/pweaver/emacs-eclim/eclim-macros.elc
Compiling /home/pweaver/emacs-eclim/eclim-maven.el...

In toplevel form:
eclim-maven.el:32:1:Error: Cannot open load file: no such file or directory, popup
Compiling /home/pweaver/emacs-eclim/eclim-problems.el...

In toplevel form:
eclim-problems.el:30:1:Error: Cannot open load file: no such file or directory, popup
Compiling /home/pweaver/emacs-eclim/eclim-project.el...

In toplevel form:
eclim-project.el:33:1:Error: Cannot open load file: no such file or directory, popup
Compiling /home/pweaver/emacs-eclim/eclim-scala.el...

In toplevel form:
eclim-scala.el:33:1:Error: Cannot open load file: no such file or directory, popup
Compiling /home/pweaver/emacs-eclim/eclim.el...

In toplevel form:
eclim.el:41:1:Error: Cannot open load file: no such file or directory, s
Compiling /home/pweaver/emacs-eclim/eclimd.el...

In toplevel form:
eclimd.el:33:1:Error: Cannot open load file: no such file or directory, popup
```

I have those packages installed (s, popup, dash), but they're not available if you run ```emacs -Q```.

**Comment by luisgerhorst** [comment] 2017-01-12 19:19
Did you run `make init`?

**Comment by nloyola** [comment] 2017-01-12 19:28
For future reference here is the link to the Cask project, it has instructions for how to install it:

* https://github.com/cask/cask

I commit instructions in the documentation on how to install it soon.

**Comment by luisgerhorst** [comment] 2017-01-12 19:29
But I can confirm that compiling without `cask` does not work. @nloyola Should this option be removed? I get the same output as @pheaver expect the first line being
```
emacs -Q -batch -L .  -l maint/eclim-compile.el -f eclim/batch-byte-compile ac-emacs-eclim.el company-emacs-eclim.el eclim-ant.el eclim-common.el eclim-completion.el eclim-debug.el eclim-java-run.el eclim-java.el eclim-macros.el eclim-maven.el eclim-pkg.el eclim-problems.el eclim-project.el eclim-scala.el eclim.el eclimd.el
```

**Comment by nloyola** [comment] 2017-01-12 19:31
@luisgerhorst So this is the problem with moving to Cask. Cask installs all the dependencies in a subdirectory. If you build without cask, emacs does not know where to find those dependencies.

**Comment by luisgerhorst** [comment] 2017-01-12 19:34
Should I remove the option for now? I can put it into https://github.com/emacs-eclim/emacs-eclim/pull/32

**Comment by nloyola** [comment] 2017-01-12 19:39
Using cask makes it easier to manage the package's dependencies and write test code. It's gaining traction with many package developers. 

@luisgerhorst I'm not sure I know which options you are referring to. Can you please clarify?

**Comment by pheaver** [comment] 2017-01-12 19:40
(let me know if there's anything I can do to help, e.g. testing any changes you make).

**Comment by luisgerhorst** [comment] 2017-01-12 19:41
@nloyola The option to compile without cask, other similar projects also don't have this option so I don't think there's a obvious way to do this.

**Comment by luisgerhorst** [comment] 2017-01-12 19:44
@pheaver Did you get it to work via melpa yet? I tried `eclim-20170107.2050` but it worked.

**Comment by nloyola** [comment] 2017-01-12 19:46
I guess it depends on the answer to this question: what is the intent of the person when they clone this repository and compile the code?

Would a non developer want to clone this repository? 

I'm still not sure if Cask is the way to go. I can always revert the Makefile and make the compile work the way it did before.

**Comment by luisgerhorst** [comment] 2017-01-12 19:54
I'm not that experienced with maintaining projects with many dependencies via GitHub, but for me Cask worked very well (I'm on Mac OS thought). How can you compile the project without cask / installing the dependencies manually anyway?

**Comment by nloyola** [comment] 2017-01-12 20:15
@pheaver Can you please try the following commands: 

```
make init
make compile
```
 And let me know what the result is?

Thanks

**Comment by nloyola** [comment] 2017-01-12 20:21
@luisgerhorst this version of the Makefile compiled without cask:

https://github.com/emacs-eclim/emacs-eclim/blob/1fea103f4f209ee89d6690ca30a417a566d1928a/Makefile

But it was really slow since it started Emacs for each file to compile.

**Comment by luisgerhorst** [comment] 2017-01-12 20:30
@nloyola Didn't this also require the user to have all dependencies installed locally in their regular config via package.el? If so this wouldn't be much better than requiring the user to install Cask.

**Comment by nloyola** [comment] 2017-01-12 20:36
@luisgerhorst actually there was some magic in [emacs-eclim-linter-init.el](https://github.com/emacs-eclim/emacs-eclim/blob/1fea103f4f209ee89d6690ca30a417a566d1928a/test/emacs-eclim-linter-init.el) that downloaded the required packages.

Yes, you are right: it's not better than requiring Cask.

**Comment by luisgerhorst** [comment] 2017-01-12 20:43
@nloyola Ah ok :D

**Comment by pheaver** [comment] 2017-01-12 21:04
@nloyola Aha! It works perfectly if I do ```make init``` once before ```make compile``` (with cask installed, from emacs-eclim commit 7dc8732).

For what it's worth, I'd vote for continuing to use cask as long as the instructions make it extremely easy for a user to install and use it.

**Closed as completed** 2017-01-12 22:43 UTC
